x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    _PIP_ADDITIONAL_REQUIREMENTS: "dbt-postgres==1.10.0 requests python-dotenv psycopg2-binary"
    RIOT_API_KEY: ${RIOT_API_KEY}
    DB_HOST: host.docker.internal
    DB_PORT: ${DB_PORT}
    DB_NAME: lol_ranked
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
  volumes:
    - ./dags:/opt/airflow/dags
    - ../extraction:/opt/airflow/extraction
    - ../loading:/opt/airflow/loading
    - ../dbt/lol_ranked_dbt:/opt/airflow/dbt/lol_ranked_dbt
    - ../data:/opt/airflow/data
  depends_on:
    postgres_airflow:
      condition: service_healthy

services:
  postgres_airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres_airflow_data: