lol_ranked_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: mordisco8
      dbname: lol_ranked
      schema: public
      threads: 1
